# Generated by Django 3.2.8 on 2022-05-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name=' عنوان مسیولیت')),
            ],
            options={
                'verbose_name': 'مسیولیت',
                'verbose_name_plural': 'لیست مسیولیت',
            },
        ),
        migrations.CreateModel(
            name='MembersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('avatar', models.ImageField(upload_to='images/team_info', verbose_name='تصویر')),
                ('url_linkedin', models.URLField(verbose_name='لینک linkedin')),
                ('url_whatsapp', models.URLField(verbose_name='لینک whatsapp')),
                ('url_telegram', models.URLField(verbose_name='لینک telegram')),
                ('url_email', models.URLField(verbose_name='لینک email')),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_info_module.responsibility', verbose_name='مسیولیت')),
            ],
        ),
    ]
