# Generated by Django 3.2.8 on 2022-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_info_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersinfo',
            options={'verbose_name': 'اعضا', 'verbose_name_plural': 'اعضای گروه'},
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='short_descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
