# Generated by Django 3.2.8 on 2022-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_info_module', '0002_auto_20220511_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersinfo',
            name='short_descriptions',
            field=models.TextField(default='this defult text,', verbose_name='توضیح کوتاه'),
            preserve_default=False,
        ),
    ]
