# Generated by Django 3.2.8 on 2022-03-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('height', models.IntegerField(verbose_name='قد')),
                ('age', models.IntegerField(verbose_name='سن')),
            ],
            options={
                'verbose_name': 'BMI',
                'verbose_name_plural': 'لیست BMI',
            },
        ),
        migrations.CreateModel(
            name='DiseaseGroupModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام بیماری')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='نام در url')),
            ],
            options={
                'verbose_name': 'بیماری',
                'verbose_name_plural': 'لیست بیماری ها',
            },
        ),
        migrations.CreateModel(
            name='FoodModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام غذا')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیخات اولیه')),
                ('raw_material', models.TextField(verbose_name='مواد اولیه')),
                ('description', models.TextField(verbose_name='طرز تهیه')),
                ('informations_food', models.TextField(blank=True, null=True, verbose_name='اطلاعات علمی در باره غذا')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='نام در url')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMI_module.diseasegroupmodels', verbose_name='گروه بیماری')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'لیست غذا',
            },
        ),
    ]
