# Generated by Django 3.2.8 on 2022-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0003_foodmodels_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMassModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام توده بدنی')),
            ],
            options={
                'verbose_name': 'توده بدنی',
                'verbose_name_plural': 'لیست توده بدنی',
            },
        ),
    ]
