# Generated by Django 3.2.8 on 2022-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0006_alter_foodmodels_body_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmimodels',
            name='gender',
            field=models.CharField(choices=[('آقا', 'آقا'), ('خانم', 'خانم')], default='آقا', max_length=20),
        ),
    ]
