# Generated by Django 3.2.8 on 2022-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0008_auto_20220403_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmimodels',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bmimodels',
            name='weight',
            field=models.FloatField(),
        ),
    ]
