# Generated by Django 3.2.8 on 2022-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0010_auto_20220404_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام گروه بیماری')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='نام در url')),
            ],
            options={
                'verbose_name': 'دسته بندی بیماری',
                'verbose_name_plural': 'دسته بندی بیماری ها',
            },
        ),
    ]
