# Generated by Django 3.2.8 on 2022-06-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0012_diseasegroupmodels_caregory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasegroupmodels',
            name='caregory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMI_module.diseasegroupmodels', verbose_name='بیماری والد'),
        ),
        migrations.DeleteModel(
            name='DiseaseCategoryGroup',
        ),
    ]
