# Generated by Django 3.2.8 on 2022-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0013_auto_20220609_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodels',
            name='image_food',
            field=models.ImageField(blank=True, null=True, upload_to='images/foods', verbose_name='تصویر'),
        ),
    ]
