# Generated by Django 3.2.8 on 2022-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0014_foodmodels_image_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodels',
            name='pdf_food',
            field=models.FileField(default='sdf', upload_to='pdf/food', verbose_name='فایل pdf'),
            preserve_default=False,
        ),
    ]
