# Generated by Django 3.2.8 on 2022-06-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0015_foodmodels_pdf_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResultModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_result', models.FileField(upload_to='video/result', verbose_name='فایل ویدیو')),
                ('name', models.CharField(max_length=300, verbose_name='نام ویدیو')),
                ('Body_mass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMI_module.bodymassmodels', verbose_name='مناسب برای توده بندی ')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'لیست ویدیو',
            },
        ),
    ]
