# Generated by Django 3.2.8 on 2022-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0016_videoresultmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کاربر')),
                ('text_comment', models.TextField(verbose_name='متن پیام')),
                ('created_comment', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('active_comment', models.BooleanField(default=False, verbose_name='فعال/ غیر فعال')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
