# Generated by Django 3.2.8 on 2022-06-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کاربر'),
        ),
    ]
