# Generated by Django 3.2.8 on 2022-06-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0018_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
