# Generated by Django 3.2.8 on 2022-04-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmodels',
            name='group',
        ),
    ]
