# Generated by Django 3.2.8 on 2022-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0002_remove_foodmodels_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodels',
            name='group',
            field=models.ManyToManyField(to='BMI_module.DiseaseGroupModels', verbose_name='گروه بیماری'),
        ),
    ]
