# Generated by Django 3.2.8 on 2022-04-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0005_foodmodels_body_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodels',
            name='Body_mass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMI_module.bodymassmodels', verbose_name='مناسب برای توده بندی '),
        ),
    ]
