# Generated by Django 3.2.8 on 2022-03-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
