# Generated by Django 3.2.8 on 2022-03-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_remove_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
