# Generated by Django 3.2.8 on 2022-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='ایدی'),
        ),
    ]
