# Generated by Django 3.2.8 on 2022-04-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_rename_body_mass_user_body_mass_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='body_mass_user',
        ),
    ]
