# Generated by Django 3.2.8 on 2022-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0019_remove_comment_name'),
        ('account_module', '0014_user_sickness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sickness',
        ),
        migrations.AddField(
            model_name='user',
            name='sickness',
            field=models.ManyToManyField(blank=True, null=True, to='BMI_module.DiseaseGroupModels', verbose_name='بیماری کاربر'),
        ),
    ]
