# Generated by Django 3.2.8 on 2022-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0016_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه'),
        ),
    ]
