# Generated by Django 3.2.8 on 2022-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0017_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile/default-profile-pic.png', null=True, upload_to='images/profile', verbose_name='تصویر آواتار'),
        ),
    ]
