# Generated by Django 3.2.8 on 2022-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_auto_20220329_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=''),
        ),
    ]
