# Generated by Django 3.2.8 on 2022-04-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='users_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ایدی'),
        ),
    ]
