# Generated by Django 3.2.8 on 2022-04-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_module', '0010_auto_20220404_0044'),
        ('account_module', '0009_user_bmi_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body_mass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMI_module.bodymassmodels', verbose_name='وضعیت توده بندی کاربر'),
        ),
    ]
