# Generated by Django 3.2.8 on 2022-04-24 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_user_body_mass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='body_mass',
            new_name='body_mass_user',
        ),
    ]
